version: '3.8'

services:
  cdn-monitor:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CF_TOKENS=${CF_TOKENS}
      - CF_ZONES=${CF_ZONES}
      - CF_DOMAINS=${CF_DOMAINS}
      - EO_SECRET_ID=${EO_SECRET_ID}
      - EO_SECRET_KEY=${EO_SECRET_KEY}
      - SITE_NAME=${SITE_NAME}
      - SITE_ICON=${SITE_ICON}
      - EO_ICON=${EO_ICON}
      - DEBUG=${DEBUG}
    restart: unless-stopped
